#!/bin/sh

# Para que vayan gráficos y audio, es necesario tener sysfs y proc.
# Y para que arranque el servicio udev/eudev/mdev, y para poder configurar el governor a mano.
# Se supone que el kernel tiene las opciones CONFIG_DEVTMPFS=y, CONFIG_DEVTMPFS_MOUNT=y,
# por lo que en /dev el propio kernel tiene ya montado el devtmpfs que es donde udev/eudev/mdev
# crean los nodos de /dev.
mount -t sysfs sysfs /sys
mount -t proc proc /proc

# Ponemos a punto el governor
echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo performance > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
echo performance > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
echo performance > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor

# Re-montamos el root como lectura/escritura.
mount -o remount,rw /

# OPCIONAL: Lanzamos udev/eudev para que nos detecte lo que conectemos dinámicamene,
# carge los modulos correspondientes y cree los nodos en /dev.
# RECUERDA que en sistemas sin systemd no existe udev, sino eudev, pero se usa igual..
/etc/init.d/udev start >> /dev/null
#/etc/init.d/eudev start >> /dev/null

# Esto de devpst es para poder conectar por ssh, si no no nos podrá dar una PTY.
#mkdir /dev/pts
#mount -t devpts none /dev/pts -o gid=4,mode=620

# MUY IMPORTANTE exportar $HOME o las configuraciones de los programas
# se empezarán a guardar en /. Así que esto hay que hacerlo SIEMPRE.
export HOME=/root

# En caso de querer consola en vez de un único programa corriendo,
# descomentar este bloque entero.
# El lanzamiento de sh se hace mediante setsid y exec en dos stages:
# En el STAGE 1, setsid inicia una nueva sesión y manda un primer sh ahí,
# y en el STAGE 2 exec ejecuta otro sh con el mismo PID que el sh anterior,
# que tiene PID 1 (Siempre hay que tener un PID 1 o el kernel da un panic
# por matar el proceso init). La entrada y salida de este segundo sh
# es redireccionada a tty1.
# Setupcon configura la fuente y el teclado de la consola,
# leyendo la configuración de /etc/default/console-setup y /etc/default/keyboard.
# Se puede usar bash o bien sh.
hostname minimal
setupcon
setsid sh -c 'cd /root;exec bash </dev/tty1 >/dev/tty1 2>&1'

# En caso de querer un único programa corriendo:
# setsid sh -c 'exec /usr/local/bin/retroarch </dev/tty1 >/dev/tty1 2>&1'

# Una vez que se sale del programa único, paramos udev/eudev (si es que lo
# hemos lanzado) y montamos el root como readonly.
# El desmontaje conlleva la sincronización de los discos.
/etc/init.d/udev stop >> /dev/null
#/etc/init.d/eudev stop >> /dev/null
mount / -o remount,ro

# Dependiendo de si quieres reiniciar o apagar al salir, usa una o la otra.
# Poweroff va con dos -f, sí, no es un error, es para que no contacte con el gestor de procesos, que no existe.
reboot -f
#poweroff -f -f
