#!/bin/sh

#################################################
# BLOQUE DEVTMPFS Y MDEV                        #
#################################################

# ¡¡¡¡CUIDADO!!!! ANTES DE PODER USAR MDEV, DEBEMOS CREAR UN LINK SIMBÓLICO A BUSYBOX CON:
# "ln -s /bin/busybox /bin/mdev"

# Para que se creen y borren automáticamente los nodos en /dev al conectar y desconectar cosas,
# lo que se usa es DEVTMPFS, que es parte del kernel. O SEA, es el kernel el que crea y borra
# los nodos en /dev, NO hace falta MDEV para ello.
# Para que funcione DEVTMPFS, el kernel ha de tener la opción CONFIG_DEVTMPFS=y, que es lo más común. 
# Y para que el kernel monte DEVTMPFS en /dev automáticamente, debe tener CONFIG_DEVTMPFS_MOUNT=y,
# que también es lo más común.
#
# Si arrancases usando un initramfs o un initrd, sin embargo, sí tendrías que montar DEVTMPFS en /dev
# a mano LO PRIMERO EN EL SCRIPT, usando "mount -t devtmpfs none /dev", y luego tendrías que
# pedirle a MDEV que recreease los nodos de dispositivo usando "busybox mdev -s", ya que aunque
# el kernel ya habría creado los nodos en /dev en el arranque, ahora estaríamos con un /dev vacío
# y habría que volver a crear los nodos: el kernel ya los creó así que no lo va volver a hacer
# a no ser que reconectásemos todo.
#
# Además, en kernels viejos, CONFIG_DEVTMPFS_MOUNT no estaba, y por eso también a veces verás
# instrucciones viejas que indican que hagas lo primero "mount -t devtmpfs none /dev" o similar.

# MDEV lo usamos para cargar automáticamente los módulos correspondientes y para establecer
# los permisos de los nodos.
# Para ello, debemos tener estas líneas en /etc/mdev.conf:
#-$MODALIAS=.* root:root 660 @modprobe "$MODALIAS"
#-$MODALIAS=.* root:root 660 $modprobe -r "$MODALIAS"
# Son dos líneas porque una es para la carga automática de módulos al CONECTAR algo y otra
# para la descarga automática de módulos al DESCONECTAR algo.
# Lo de 'root:root 660' es la propiedad (usuario:grupo) y los permisos de los nodos. 
# Ambas líneas empiezan por un guión realmente, para que MDEV no se detenga en la primera en que
# haga match, y aunque parezca raro, en la de descarga también hay que poner la propiedad
# y los permisos o no funciona.
# Para que un comando se ejecute cuando se CONECTA algo se precede de '@' y para que se ejecute
# cuando se DESCONECTA algo se precede de '$'. Por eso tienes una '@' en la de carga y un '$'
# en la de descarga.
# Se necesitan LAS DOS LÍNEAS, no vale poner el comando de carga (@modprobe) y el de descarga
# ($modprobe -r) en la misma, sencillamente NO FUNCIONA.
# Y con lo siguiente le decimos al kernel que llame a MDEV cuando haya un hotplug/unplug:
echo /bin/mdev > /proc/sys/kernel/hotplug

# Para que vayan gráficos y audio, es necesario tener sysfs y proc montados.
# En algunos kernels, como el de Devuan, ya viene montado /sys, así que la línea de montaje de /sys
# la tengo comentada por eso.
# mount -t sysfs none /sys
mount -t proc proc /proc

# El sistema devpts (NO confundir con el gran DEVTMPFS, ¡ojo!) es otro sistema de archivos virtual
# que vive en /dev/pts y que contiene esclavos multiplexados de /dev/ptmx, siendo cada uno de esos
# esclavos la representación de un emulador de terminal (como xterm en X11,
# o un terminal de wayland, o un terminal de acceso por SSH. Como usamos SSH,
# pues tenemos que montar esto o nos dará un error "PTY allocation failed" al intentar entrar).
mkdir -p /dev/pts
mount devpts /dev/pts -t devpts

# Cargamos los módulos del hardware que YA tenemos conectado. ¿Por qué lo hacemos a mano? Pues mira:
# Cuando conectemos nuevo hardware, se encargará MDEV porque será llamado por el kernel en cada evento
# de conexión/desconexión, pero para el hardware que YA está conectado al arrancar, lo tenemos que
# hacer nosotros porque no hay tales eventos que desencadenen las llamadas a MDEV.
find /sys/devices -name modalias -type f -print0 | xargs -0 sort -u | xargs modprobe -ab 2>/dev/null

#################################################
# FIN BLOQUE DEVTMPFS Y MDEV                    #
#################################################

# Ponemos a punto el governor de cada core, ahora que ya tenemos el sysfs preparado
# y cargados los módulos que permiten controlar la frecuencia de la CPU de la Pi.
for numcore in 0 1 2 3
do
 echo performance > /sys/devices/system/cpu/cpu$numcore/cpufreq/scaling_governor
done

# Re-montamos el root como lectura/escritura.
# Añadimos la opción "sync" después de otra coma para que las escrituras sean inmediatas,
# lo que mejora mucho la predictibilidad del sistema al no haber escrituras retardadas.
mount -o remount,rw,sync,noatime,nodiratime /

# Montamos también la partición de BOOT
mount /dev/mmcblk0p10 /boot -o rw,sync,noatime,nodiratime

# Montamos /tmpfs y /var/log en RAM, para que no se escriban temporales ni logs
# en disco.
# OJO, no especificamos un tamaño, así que como mucho pueden ocupar el 50% de la RAM.
mount -t tmpfs tmpfs /tmp
mount -t tmpfs tmpfs /var/log

# MUY IMPORTANTE exportar $HOME o las configuraciones de los programas
# se empezarán a guardar en /. Así que esto hay que hacerlo SIEMPRE.
export HOME=/root

# Setupcon configura la fuente y el teclado de la consola,
# leyendo la configuración de /etc/default/console-setup y /etc/default/keyboard.
hostname minimal
setupcon

# Restablecemos la última fecha conocida de /etc/fake-hwclock.data, para que
# al menos no estemos en los 70s. Importante para qie GIT funcione.
fake-hwclock load >> /dev/null

# Antes de establecer el volúmen, tenemos que reproducir un audio aunque sea
# inexistente, o el controlador del volúmen por software (softvol) no estará
# disponible aún.
# Algunos dispositivos como el vc4hdmi no tienen control de volúmen por hw.
aplay  /dev/zero -s 1 -q
amixer set PCM 230 -q

# El lanzamiento del bash se hace mediante setsid y exec en dos stages:
# En el STAGE 1, setsid inicia una nueva sesión y manda un primer sh ahí,
# y en el STAGE 2 exec ejecuta otro sh con el mismo PID que el sh anterior,
# que tiene PID 1 (Siempre hay que tener un PID 1 o el kernel da un panic
# por matar el proceso init). La entrada y salida de este segundo sh
# es redireccionada a tty1.
# Se puede usar bash o bien sh. Si usamos bash, hay que pasarle el --login
# porque si no, no lee /etc/profile y nos faltan cosas en el $PATH.
setsid sh -c 'cd /root;exec bash --login </dev/tty1 >/dev/tty1 2>&1'

# En caso de querer un único programa corriendo:
# setsid sh -c 'exec /usr/local/bin/retroarch </dev/tty1 >/dev/tty1 2>&1'

# Salvamos la última fecha conocida, que va al fichero /etc/fake-hwclock.data
fake-hwclock save

# Matamos todos los procesos que se han lanzado desde este script,
# para que no haya nada accediendo a directorios que cuelguen del rootfs.
pkill -P 1

# Desmontamos todo lo que hemos montado.
# El desmontaje conlleva la sincronización de los discos.
umount /sys
umount /proc
umount /tmp
umount /var/log
umount /boot

# El desmontaje del rootfs de un kernel en ejecución no se supone que sea posible,
# así que lo re-montamos como sólo lectura y así el kernel puede seguir usándolo aunque
# ya no se pueda escribir en él.
# (Una alternativa sería hacer un swicth_root a un rootfs en initramfs).
# NOTA: El bucle de espera en realidad no debería ser necesario porque ahí arriba has matado
# todos los procesos lanzados por este script así que no debe haber nada accediendo a
# directorios que cuelguen de /, pero se deja a modo de documentación.
# IMPORTANTE: El re-montaje falla SIEMPRE si has editado este fichero mientras el
# sistema lo estaba usando. Para confirmar que sigue abierto usa "lsof|grep minimal".
busy=true
while $busy
do
  mount / -o remount,ro 2> /dev/null
  if [ $? -eq 0 ] # Si el último comando ejecutado tuvo éxito, $? es 0. 
  then
   busy=false
   echo Filesystem umount successfull.
  else
   echo -n '.'  # Escribimos algo para que se vea que el script sigue vivo.
   sleep 1      # Esperamos un segundo a reintentar.
  fi  
done

# Dependiendo de si quieres reiniciar o apagar al salir, usa una o la otra.
# Poweroff va con dos -f, sí, no es un error, es para que no contacte con el
# gestor de procesos, que no existe.
reboot -f
#poweroff -f -f
